version: "3.9"

services:
  db:
    image: postgres
    container_name: rotandruin-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fjmqli
      POSTGRES_DB: rotandruin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  productservice:
    build:
      context: ./ProductService
      dockerfile: Dockerfile
    container_name: product-service
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=rotandruin;Username=postgres;Password=fjmqli
    ports:
      - "5000:8080"
    volumes:
      - ./ProductService:/app
      - ./.nuget/packages:/root/.nuget/packages
    depends_on:
      - db
    entrypoint: ["dotnet", "watch", "run", "--no-launch-profile", "ProductService.dll"]

volumes:
  postgres_data:
